using PrintEcho.SDK;
using Stimulsoft.Report;

namespace Samples.PrintEcho.CustomFunctions;

public class DemoFunctions
{
    /// <summary>
    /// 定义您的自定义函数
    /// </summary>
    [CustomFunction("示例",
        Description = "这是函数描述",
        ReturnDescription = "这是返回值描述",
        ArgumentNames = ["name"],
        ArgumentDescriptions = ["名称"])]
    public static string GetText(string name)
    {
        return $"Hi {name}, this message is generated by your custom function '{nameof(GetText)}'.";
    }

    /// <summary>
    /// 获取报表别名
    /// </summary>
    [CustomFunction("示例",
        Description = "获取报表别名",
        ReturnDescription = "报表别名")]
    public static string GetReportAlias()
    {
        var report = PrintContext<StiReport>.Current;
        return $"The report alias is {report?.ReportAlias}";
    }
}